spring:
  application:
    name: art-server
  profiles:
    active: secrets
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  api:
    gyeonggikey: ${GYEONGGI_API_KEY}
    gonggongkey: ${GONGGONG_API_KEY}
  logging:
    level:
     com.doma.artserver.controller.ExhibitionController: INFO

  major-museums:
    names:
      - 국립중앙박물관
      - 국립현대미술관 서울관
      - 국립현대미술관 과천관
      - 서울시립미술관
      - 국립아시아문화전당