spring:
  application:
    name: art-server
  profiles:
    active: secrets
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  api:
    gyeonggikey: ${GYEONGGI_API_KEY}
    gonggongkey: ${GONGGONG_API_KEY}
  logging:
    level:
     com.doma.artserver.controller.ExhibitionController: INFO
  gcp:
    project-id: ${GCP_PROJECT_ID}
    storage:
      bucket-name: art-bucket
  data:
#    redis:
#      host: ${REDIS_HOST} # Redis 서버의 호스트 (기본값 localhost)
#      port: 6379       # Redis 서버의 포트 (기본값 6379)
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          time-between-eviction-runs: 30000ms
#        shutdown-timeout: 100ms

major-museums:
  names:
    - 국립중앙박물관
    - 국립현대미술관 서울관
    - 국립현대미술관 과천관
    - 서울시립미술관

