name: Spring Boot GCP Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Build Docker Image
      run: docker build -t art-server .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag art-server ${{ secrets.DOCKER_HUB_USERNAME }}/art-server:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/art-server:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: SSH to GCP and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_SERVER_URL }}
        username: ${{ secrets.GCP_SSH_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          # 기존 컨테이너 정지 및 제거
          sudo docker stop art-server || true
          sudo docker rm art-server || true

          # Docker Hub에서 최신 이미지 가져오기
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/art-server:latest

          # 컨테이너 실행
          sudo docker run --rm -d -p 80:8080 --name art-server ${{ secrets.DOCKER_HUB_USERNAME }}/art-server:latest
